version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn install
  post_build:
    commands:
      - echo Build completed successfully
      - mv appspec.yml target/
artifacts:
  files: 
    - target/SampleMavenTomcatApp.war
    - target/appspec.yml
    - setup.sh
  discard-paths: yes
